### ISSUE TITLE
Installation TypeError in the extraction_test.py

### ISSUE THREAD

**Issue by csbobby** [google-deepmind/streamingqa#3]
Hi Could you helpt to fix the installation issue? @tayfunterzi 
The directory path is: `ROOT_PATH/streamingqa/`. The downloaded 4 data files are in the same directory with the extraction_test.py.

```
Requirement already satisfied: absl-py==1.0.0 in ./streamingqa_env/lib/python3.6/site-packages (from -r requirements.txt (line 7)) (1.0.0)
Requirement already satisfied: appdirs==1.4.4 in ./streamingqa_env/lib/python3.6/site-packages (from -r requirements.txt (line 11)) (1.4.4)
Requirement already satisfied: fs==2.4.15 in ./streamingqa_env/lib/python3.6/site-packages (from -r requirements.txt (line 15)) (2.4.15)
Requirement already satisfied: pytz==2021.3 in ./streamingqa_env/lib/python3.6/site-packages (from -r requirements.txt (line 19)) (2021.3)
Requirement already satisfied: six==1.16.0 in ./streamingqa_env/lib/python3.6/site-packages (from -r requirements.txt (line 25)) (1.16.0)
Requirement already satisfied: setuptools in ./streamingqa_env/lib/python3.6/site-packages (from fs==2.4.15->-r requirements.txt (line 15)) (39.2.0)
Requirement already satisfied: dataclasses in ./streamingqa_env/lib/python3.6/site-packages (0.8)

Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/shared/dataset/StreamingQA/streamingqa/extraction_test.py", line 35, in <module>
    @dataclasses.dataclass(frozen=True)
  File "/shared/dataset/StreamingQA/streamingqa/extraction_test.py", line 37, in _ArchiveFileInput
    docs: list[_WMTDocInput]
TypeError: 'type' object is not subscriptable
```

**Comment by tayfunterzi** [comment]
Hi @csbobby,

Thanks for reaching out.

Apologies for not declaring it specifically: it looks like we would require Python 3.9 and above. Alternatively if you like, you could either just remove the type annotations or replace them using the typing library, e.g., `typing.List`.

Let me know if that doesn't work for you.

Cheers,
Tayfun

**Comment by csbobby** [comment]
Thank you. It does not report the error after using a new virtual env with py3.9 instead of the default "streamingqa_env" in the repo.
The extraction_test has other errors
1. where are the links of the mentioned files in the extraction_test.py (such as `deduplicated_wmt_sorting_keys_file_name = 'wmt_ids.gz'`, archive_file_input.file_names`news-docs.2019.en.filtered.gz` or `news-docs.2020.en.filtered.gz`) ?

2. The extraction_test reports another issue:

```
Requirement already satisfied: dataclasses in ./sqa_env/lib/python3.9/site-packages (0.6)
Running tests under Python 3.9.16: /shared/dataset/StreamingQA/streamingqa/sqa_env/bin/python3
[ RUN      ] ExtractionTest.test_get_wmt_docs_from_archive_file_paths
[       OK ] ExtractionTest.test_get_wmt_docs_from_archive_file_paths
[ RUN      ] ExtractionTest.test_get_wmt_passages_from_docs
[  FAILED  ] ExtractionTest.test_get_wmt_passages_from_docs
======================================================================
FAIL: test_get_wmt_passages_from_docs (__main__.ExtractionTest)
ExtractionTest.test_get_wmt_passages_from_docs
----------------------------------------------------------------------
Traceback (most recent call last):
  File "shared/dataset/StreamingQA/streamingqa/extraction_test.py", line 150, in test_get_wmt_passages_from_docs
    self.assertEqual([
AssertionError: Lists differ: [WMTP[23 chars]xt=b'Thursday, January 1, 1970. 1. 2. 3. 4. 5.[66 chars]7.')] != [WMTP[23 chars]xt=b'Wednesday, December 31, 1969. 1. 2. 3. 4.[72 chars]7.')]

First differing element 0:
WMTPa[13 chars]_0_0', text=b'Thursday, January 1, 1970. 1. 2. 3. 4. 5. 6.')
WMTPa[13 chars]_0_0', text=b'Wednesday, December 31, 1969. 1. 2. 3. 4. 5. 6.')

- [WMTPassage(id='doc_0_0', text=b'Thursday, January 1, 1970. 1. 2. 3. 4. 5. 6.'),
?                                  ^^^^      ^^^^^ ^^     ^^

+ [WMTPassage(id='doc_0_0', text=b'Wednesday, December 31, 1969. 1. 2. 3. 4. 5. 6.'),
?                                  ^^^^^      ^^^^^^^ ^^     ^^

-  WMTPassage(id='doc_0_1', text=b'Thursday, January 1, 1970. 7.')]
?                                  ^^^^      ^^^^^ ^^     ^^

+  WMTPassage(id='doc_0_1', text=b'Wednesday, December 31, 1969. 7.')]
?                                  ^^^^^      ^^^^^^^ ^^     ^^


----------------------------------------------------------------------
Ran 2 tests in 0.004s

FAILED (failures=1)
```

**Comment by tayfunterzi** [comment]
Hi @csbobby,

You can find the needed WMT files following the link and instruction as shown in the README under the WMT header (https://github.com/google-deepmind/streamingqa#wmt). For instance, I can see the right files at the Index of `.../news-crawl/doc/en/` as instructed via the link.
The other files you need you'll also find in the README under the Download header at https://github.com/google-deepmind/streamingqa#download. The rightmost column "Download" provides the links for these.

For your failing tests, it looks like we omitted specifically declaring the UTC time zone when creating the datetime object from timestamp. I'll modify the code and upload it. I hope this should fix it for you.

Cheers,
Tayfun
